import React, { createContext, useState, useContext, ReactNode } from "react";

type Language = {
  code: string;
  name: string;
  direction: "rtl" | "ltr";
};

type LanguageContextType = {
  currentLanguage: Language;
  availableLanguages: Language[];
  changeLanguage: (code: string) => void;
  t: (key: string) => string;
};

const availableLanguages: Language[] = [
  { code: "en", name: "English", direction: "ltr" },
  { code: "ar", name: "العربية", direction: "rtl" },
  { code: "fr", name: "Français", direction: "ltr" },
  { code: "es", name: "Español", direction: "ltr" },
];

// Translation dictionaries
const translations: Record<string, Record<string, string>> = {
  en: {
    home: "Home",
    services: "Services",
    providers: "Providers",
    about: "About",
    signIn: "Sign In",
    findService: "Find the Perfect Service",
    connectProviders:
      "Connect with verified service providers across multiple categories for all your needs",
    browseCategories: "Browse Categories",
    accommodation: "Accommodation",
    retail: "Retail",
    restaurants: "Restaurants",
    maintenance: "Maintenance",
    transportation: "Transportation",
    investments: "Investments",
    featuredServices: "Featured Services",
    viewAll: "View All",
    howItWorks: "How It Works",
    searchServices: "Search Services",
    connect: "Connect",
    enjoyReview: "Enjoy & Review",
    searchStep:
      "Browse categories or search for specific services in your area",
    connectStep: "Choose from verified service providers and book directly",
    reviewStep: "Experience quality service and share your feedback",
    testimonials: "What Our Users Say",
    becomeProvider: "Become a Provider",
    readyOffer: "Ready to offer your services?",
    joinCommunity:
      "Join our growing community of service providers and reach thousands of potential customers",
    profile: "Profile",
    settings: "Settings",
    myBookings: "My Bookings",
    logout: "Logout",
    digitalCurrency: "Digital Currency",
    wallet: "Wallet",
    rewards: "Rewards",
    myServices: "My Services",
    dashboard: "Dashboard",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    signInAccess: "Sign in to access your account",
    joinPlatform: "Join our marketplace platform",
    customer: "Customer",
    serviceProvider: "Service Provider",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    rememberMe: "Remember me for 30 days",
    firstName: "First Name",
    lastName: "Last Name",
    confirmPassword: "Confirm Password",
    agreeToTerms: "I agree to the",
    termsOfService: "Terms of Service",
    and: "and",
    privacyPolicy: "Privacy Policy",
    businessEmail: "Business Email",
    businessName: "Business Name",
    businessType: "Business Type",
    newToPlatform: "New to our platform?",
    alreadyHaveAccount: "Already have an account?",
    identityVerification: "Identity Verification",
    verifyIdentity: "Verify your identity to access our services",
    completeVerification: "Complete verification to become a service provider",
    personalInfo: "Personal Information",
    documentVerification: "Document Verification",
    selfieVerification: "Selfie Verification",
    businessVerification: "Business Verification",
    next: "Next",
    back: "Back",
    complete: "Complete",
    retailStores: "Retail Stores",
    searchStores: "Search for stores, products, or categories...",
    location: "Location",
    filter: "Filter",
    distance: "Distance",
    storeType: "Store Type",
    preferences: "Preferences",
    onlineStoresOnly: "Online stores only",
    localStoresOnly: "Local stores only",
    applyFilters: "Apply Filters",
    online: "Online",
    viewStore: "View Store",
    noStoresFound: "No stores found matching your criteria",
    resetFilters: "Reset Filters",
    previous: "Previous",
    next: "Next",
    details: "Details",
    products: "Products",
    reviews: "Reviews",
    aboutStore: "About the Store",
    storeInformation: "Store Information",
    openingHours: "Opening Hours",
    features: "Features & Amenities",
    searchProducts: "Search products...",
    outOfStock: "Out of Stock",
    addToCart: "Add to Cart",
    notifyMe: "Notify Me",
    noProductsFound: "No products found matching your search",
    clearSearch: "Clear Search",
    storeLocation: "Store Location",
    mapPlaceholder: "Map would be displayed here",
    directions: "Directions",
    directionsPlaceholder:
      "Directions and transportation options would be shown here.",
    customerReviews: "Customer Reviews",
    writeReview: "Write a Review",
    reviewsPlaceholder: "Customer reviews would be displayed here.",
    saveToFavorites: "Save to Favorites",
    share: "Share",
    shopNow: "Shop Now",
    grocery: "Grocery",
    groceryStore: "Grocery Store",
    cart: "Cart",
    deliveryInfo: "Delivery Info",
    deliveryOptions: "Delivery Options",
    deliveryTime: "Delivery Time",
    deliveryTimeDescription:
      "Same day delivery for orders before 2 PM, next day for later orders.",
    deliveryFee: "Delivery Fee",
    deliveryFeeDescription:
      "Free delivery for orders over $30, otherwise $5 delivery fee.",
    paymentOptions: "Payment Options",
    paymentOptionsDescription: "Pay online or cash on delivery.",
    all: "All",
    fruits: "Fruits",
    vegetables: "Vegetables",
    dairy: "Dairy",
    meat: "Meat",
    bakery: "Bakery",
    beverages: "Beverages",
    snacks: "Snacks",
    household: "Household",
    off: "OFF",
    per: "per",
    add: "Add",
    items: "items",
    viewCart: "View Cart",
    checkout: "Checkout",
    clearFilters: "Clear Filters",
    transportationServices: "Transportation Services",
    delivery: "Delivery",
    ride: "Ride",
    pickupLocation: "Pickup Location",
    dropoffLocation: "Dropoff Location",
    enterPickupAddress: "Enter pickup address",
    enterDropoffAddress: "Enter dropoff address",
    destination: "Destination",
    enterDestination: "Enter destination",
    rideOptions: "Ride Options",
    unavailable: "Unavailable",
    selected: "Selected",
    estimatedTotal: "Estimated Total",
    continueToPayment: "Continue to Payment",
    bookRide: "Book Ride",
    paymentMethods: "Payment Methods",
    securePayment: "Secure Payment",
    creditCard: "Credit Card",
    cashOnDelivery: "Cash on Delivery",
    cash: "Cash",
    retailIntegration: "Integration with Retail & Grocery",
    retailIntegrationDescription:
      "Our delivery services are fully integrated with retail and grocery stores. When you make a purchase, you can select one of our delivery options directly at checkout.",
    learnMore: "Learn More",
    deliveryAvailable: "Delivery Available",
    deliveryOptionsAvailable:
      "Multiple delivery options available for this store.",
    viewDeliveryOptions: "View delivery options",
    viewGroceryStore: "View grocery store",
  },
  ar: {
    home: "الرئيسية",
    services: "الخدمات",
    providers: "مقدمي الخدمات",
    about: "حول",
    signIn: "تسجيل الدخول",
    findService: "ابحث عن الخدمة المثالية",
    connectProviders:
      "تواصل مع مقدمي خدمات موثوقين عبر فئات متعددة لتلبية جميع احتياجاتك",
    browseCategories: "تصفح الفئات",
    accommodation: "الإقامة",
    retail: "التجزئة",
    restaurants: "المطاعم",
    maintenance: "الصيانة",
    transportation: "النقل",
    investments: "الاستثمارات",
    featuredServices: "الخدمات المميزة",
    viewAll: "عرض الكل",
    howItWorks: "كيف يعمل",
    searchServices: "البحث عن الخدمات",
    connect: "التواصل",
    enjoyReview: "الاستمتاع والتقييم",
    searchStep: "تصفح الفئات أو ابحث عن خدمات محددة في منطقتك",
    connectStep: "اختر من بين مقدمي الخدمات الموثوقين واحجز مباشرة",
    reviewStep: "استمتع بخدمة عالية الجودة وشارك تقييمك",
    testimonials: "ماذا يقول مستخدمونا",
    becomeProvider: "كن مقدم خدمة",
    readyOffer: "هل أنت مستعد لتقديم خدماتك؟",
    joinCommunity:
      "انضم إلى مجتمعنا المتنامي من مقدمي الخدمات وتواصل مع آلاف العملاء المحتملين",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    myBookings: "حجوزاتي",
    logout: "تسجيل الخروج",
    digitalCurrency: "العملة الرقمية",
    wallet: "المحفظة",
    rewards: "المكافآت",
    myServices: "خدماتي",
    dashboard: "لوحة التحكم",
    welcomeBack: "مرحبًا بعودتك",
    createAccount: "إنشاء حساب",
    signInAccess: "تسجيل الدخول للوصول إلى حسابك",
    joinPlatform: "انضم إلى منصتنا",
    customer: "عميل",
    serviceProvider: "مقدم خدمة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    rememberMe: "تذكرني لمدة 30 يومًا",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    confirmPassword: "تأكيد كلمة المرور",
    agreeToTerms: "أوافق على",
    termsOfService: "شروط الخدمة",
    and: "و",
    privacyPolicy: "سياسة الخصوصية",
    businessEmail: "البريد الإلكتروني للعمل",
    businessName: "اسم العمل",
    businessType: "نوع العمل",
    newToPlatform: "جديد في منصتنا؟",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    identityVerification: "التحقق من الهوية",
    verifyIdentity: "تحقق من هويتك للوصول إلى خدماتنا",
    completeVerification: "أكمل التحقق لتصبح مزود خدمة",
    personalInfo: "المعلومات الشخصية",
    documentVerification: "التحقق من المستندات",
    selfieVerification: "التحقق من الصورة الشخصية",
    businessVerification: "التحقق من الأعمال",
    next: "التالي",
    back: "السابق",
    complete: "إكمال",
    retailStores: "متاجر التجزئة",
    searchStores: "ابحث عن متاجر، منتجات، أو فئات...",
    location: "الموقع",
    filter: "تصفية",
    distance: "المسافة",
    storeType: "نوع المتجر",
    preferences: "التفضيلات",
    onlineStoresOnly: "المتاجر الإلكترونية فقط",
    localStoresOnly: "المتاجر المحلية فقط",
    applyFilters: "تطبيق الفلاتر",
    online: "متجر إلكتروني",
    viewStore: "عرض المتجر",
    noStoresFound: "لا توجد متاجر تطابق معايير البحث",
    resetFilters: "إعادة ضبط الفلاتر",
    previous: "السابق",
    next: "التالي",
    details: "التفاصيل",
    products: "المنتجات",
    reviews: "التقييمات",
    aboutStore: "عن المتجر",
    storeInformation: "معلومات المتجر",
    openingHours: "ساعات العمل",
    features: "الميزات والمرافق",
    searchProducts: "البحث عن منتجات...",
    outOfStock: "غير متوفر",
    addToCart: "أضف إلى السلة",
    notifyMe: "أعلمني عند التوفر",
    noProductsFound: "لا توجد منتجات تطابق بحثك",
    clearSearch: "مسح البحث",
    storeLocation: "موقع المتجر",
    mapPlaceholder: "سيتم عرض الخريطة هنا",
    directions: "الاتجاهات",
    directionsPlaceholder: "سيتم عرض الاتجاهات وخيارات النقل هنا.",
    customerReviews: "تقييمات العملاء",
    writeReview: "كتابة تقييم",
    reviewsPlaceholder: "سيتم عرض تقييمات العملاء هنا.",
    saveToFavorites: "حفظ في المفضلة",
    share: "مشاركة",
    shopNow: "تسوق الآن",
    grocery: "البقالة",
    groceryStore: "متجر البقالة",
    cart: "سلة التسوق",
    deliveryInfo: "معلومات التوصيل",
    deliveryOptions: "خيارات التوصيل",
    deliveryTime: "وقت التوصيل",
    deliveryTimeDescription:
      "توصيل في نفس اليوم للطلبات قبل الساعة 2 مساءً، واليوم التالي للطلبات المتأخرة.",
    deliveryFee: "رسوم التوصيل",
    deliveryFeeDescription:
      "توصيل مجاني للطلبات التي تزيد عن 30 دولارًا، وإلا رسوم توصيل 5 دولارات.",
    paymentOptions: "خيارات الدفع",
    paymentOptionsDescription: "الدفع عبر الإنترنت أو الدفع عند الاستلام.",
    all: "الكل",
    fruits: "فواكه",
    vegetables: "خضروات",
    dairy: "ألبان",
    meat: "لحوم",
    bakery: "مخبوزات",
    beverages: "مشروبات",
    snacks: "وجبات خفيفة",
    household: "مستلزمات منزلية",
    off: "خصم",
    per: "لكل",
    add: "إضافة",
    items: "عناصر",
    viewCart: "عرض السلة",
    checkout: "إتمام الشراء",
    clearFilters: "مسح الفلاتر",
    transportationServices: "خدمات النقل",
    delivery: "توصيل",
    ride: "توصيل ركاب",
    pickupLocation: "موقع الاستلام",
    dropoffLocation: "موقع التسليم",
    enterPickupAddress: "أدخل عنوان الاستلام",
    enterDropoffAddress: "أدخل عنوان التسليم",
    destination: "الوجهة",
    enterDestination: "أدخل الوجهة",
    rideOptions: "خيارات الركوب",
    unavailable: "غير متاح",
    selected: "تم الاختيار",
    estimatedTotal: "المجموع التقديري",
    continueToPayment: "متابعة للدفع",
    bookRide: "حجز رحلة",
    paymentMethods: "طرق الدفع",
    securePayment: "دفع آمن",
    creditCard: "بطاقة ائتمان",
    cashOnDelivery: "الدفع عند الاستلام",
    cash: "نقدًا",
    retailIntegration: "التكامل مع متاجر التجزئة والبقالة",
    retailIntegrationDescription:
      "خدمات التوصيل لدينا متكاملة بالكامل مع متاجر التجزئة والبقالة. عند إجراء عملية شراء، يمكنك اختيار أحد خيارات التوصيل لدينا مباشرة عند الدفع.",
    learnMore: "معرفة المزيد",
    deliveryAvailable: "التوصيل متاح",
    deliveryOptionsAvailable: "تتوفر خيارات توصيل متعددة لهذا المتجر.",
    viewDeliveryOptions: "عرض خيارات التوصيل",
    viewGroceryStore: "عرض متجر البقالة",
  },
  fr: {
    home: "Accueil",
    services: "Services",
    providers: "Fournisseurs",
    about: "À propos",
    signIn: "Connexion",
    findService: "Trouvez le Service Parfait",
    connectProviders:
      "Connectez-vous avec des fournisseurs de services vérifiés dans plusieurs catégories pour tous vos besoins",
    browseCategories: "Parcourir les Catégories",
    accommodation: "Hébergement",
    retail: "Commerce",
    restaurants: "Restaurants",
    maintenance: "Maintenance",
    transportation: "Transport",
    investments: "Investissements",
    featuredServices: "Services en Vedette",
    viewAll: "Voir Tout",
    howItWorks: "Comment Ça Marche",
    searchServices: "Rechercher des Services",
    connect: "Se Connecter",
    enjoyReview: "Profiter et Évaluer",
    searchStep:
      "Parcourez les catégories ou recherchez des services spécifiques dans votre région",
    connectStep:
      "Choisissez parmi des fournisseurs de services vérifiés et réservez directement",
    reviewStep: "Profitez d'un service de qualité et partagez votre avis",
    testimonials: "Ce que disent nos utilisateurs",
    becomeProvider: "Devenir Fournisseur",
    readyOffer: "Prêt à offrir vos services?",
    joinCommunity:
      "Rejoignez notre communauté croissante de fournisseurs de services et atteignez des milliers de clients potentiels",
    profile: "Profil",
    settings: "Paramètres",
    myBookings: "Mes Réservations",
    logout: "Déconnexion",
    digitalCurrency: "Monnaie Numérique",
    wallet: "Portefeuille",
    rewards: "Récompenses",
    myServices: "Mes Services",
    dashboard: "Tableau de Bord",
    welcomeBack: "Bienvenue à nouveau",
    createAccount: "Créer un compte",
    signInAccess: "Connectez-vous pour accéder à votre compte",
    joinPlatform: "Rejoignez notre plateforme",
    customer: "Client",
    serviceProvider: "Fournisseur de services",
    email: "Email",
    password: "Mot de passe",
    forgotPassword: "Mot de passe oublié?",
    rememberMe: "Se souvenir de moi pendant 30 jours",
    firstName: "Prénom",
    lastName: "Nom",
    confirmPassword: "Confirmer le mot de passe",
    agreeToTerms: "J'accepte les",
    termsOfService: "Conditions d'utilisation",
    and: "et",
    privacyPolicy: "Politique de confidentialité",
    businessEmail: "Email professionnel",
    businessName: "Nom de l'entreprise",
    businessType: "Type d'entreprise",
    newToPlatform: "Nouveau sur notre plateforme?",
    alreadyHaveAccount: "Vous avez déjà un compte?",
    identityVerification: "Vérification d'identité",
    verifyIdentity: "Vérifiez votre identité pour accéder à nos services",
    completeVerification:
      "Complétez la vérification pour devenir un fournisseur de services",
    personalInfo: "Informations personnelles",
    documentVerification: "Vérification des documents",
    selfieVerification: "Vérification par selfie",
    businessVerification: "Vérification d'entreprise",
    next: "Suivant",
    back: "Retour",
    complete: "Terminer",
  },
  es: {
    home: "Inicio",
    services: "Servicios",
    providers: "Proveedores",
    about: "Acerca de",
    signIn: "Iniciar Sesión",
    findService: "Encuentra el Servicio Perfecto",
    connectProviders:
      "Conéctate con proveedores de servicios verificados en múltiples categorías para todas tus necesidades",
    browseCategories: "Explorar Categorías",
    accommodation: "Alojamiento",
    retail: "Comercio",
    restaurants: "Restaurantes",
    maintenance: "Mantenimiento",
    transportation: "Transporte",
    investments: "Inversiones",
    featuredServices: "Servicios Destacados",
    viewAll: "Ver Todo",
    howItWorks: "Cómo Funciona",
    searchServices: "Buscar Servicios",
    connect: "Conectar",
    enjoyReview: "Disfrutar y Reseñar",
    searchStep: "Explora categorías o busca servicios específicos en tu área",
    connectStep:
      "Elige entre proveedores de servicios verificados y reserva directamente",
    reviewStep: "Disfruta de un servicio de calidad y comparte tu opinión",
    testimonials: "Lo que dicen nuestros usuarios",
    becomeProvider: "Conviértete en Proveedor",
    readyOffer: "¿Listo para ofrecer tus servicios?",
    joinCommunity:
      "Únete a nuestra creciente comunidad de proveedores de servicios y llega a miles de clientes potenciales",
    profile: "Perfil",
    settings: "Configuración",
    myBookings: "Mis Reservas",
    logout: "Cerrar Sesión",
    digitalCurrency: "Moneda Digital",
    wallet: "Billetera",
    rewards: "Recompensas",
    myServices: "Mis Servicios",
    dashboard: "Panel de Control",
    welcomeBack: "Bienvenido de nuevo",
    createAccount: "Crear cuenta",
    signInAccess: "Inicia sesión para acceder a tu cuenta",
    joinPlatform: "Únete a nuestra plataforma",
    customer: "Cliente",
    serviceProvider: "Proveedor de servicios",
    email: "Correo electrónico",
    password: "Contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    rememberMe: "Recordarme durante 30 días",
    firstName: "Nombre",
    lastName: "Apellido",
    confirmPassword: "Confirmar contraseña",
    agreeToTerms: "Acepto los",
    termsOfService: "Términos de servicio",
    and: "y",
    privacyPolicy: "Política de privacidad",
    businessEmail: "Correo electrónico de empresa",
    businessName: "Nombre de la empresa",
    businessType: "Tipo de empresa",
    newToPlatform: "¿Nuevo en nuestra plataforma?",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    identityVerification: "Verificación de identidad",
    verifyIdentity: "Verifica tu identidad para acceder a nuestros servicios",
    completeVerification:
      "Completa la verificación para convertirte en proveedor de servicios",
    personalInfo: "Información personal",
    documentVerification: "Verificación de documentos",
    selfieVerification: "Verificación con selfie",
    businessVerification: "Verificación de negocio",
    next: "Siguiente",
    back: "Atrás",
    complete: "Completar",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({
  children,
}) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>(
    availableLanguages[0],
  );

  const changeLanguage = (code: string) => {
    const language = availableLanguages.find((lang) => lang.code === code);
    if (language) {
      setCurrentLanguage(language);
      document.documentElement.dir = language.direction;
      document.documentElement.lang = language.code;
    }
  };

  const t = (key: string): string => {
    return (
      translations[currentLanguage.code]?.[key] || translations.en[key] || key
    );
  };

  return (
    <LanguageContext.Provider
      value={{ currentLanguage, availableLanguages, changeLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
